### PR TITLE
Removing of side panel

### LINKED ISSUE #129: Remove the right-side panel
The right side panel is used rarely in the game.
Its upper half is used only by the chatter and its lower half is unused.
Additionally, completely remove any item entry code which uses the lower right panel,
and refactor the chatter and its GUI to use fullscreen tabs.

### PR DESCRIPTION
**Pull request by Hackerfiera**
fixes #129

### CODE REVIEW

**Comment by Hackerfiera** [comment]
i saw what you wrote about the dialogs, but i didn't understand it well. What do you mean with that?? @Monniasza

**Comment by Monniasza** [comment]
There should not be a tabbed pane with dialogs in the outer tabbed pane, the dialogs should appear in the outer tabbed pane instead.

**Comment by Monniasza** [comment]
@Hackerfiera Replace calls to openDialogWindow() with openAndShowWindow() and closeDialogWindow() with closeWindow() and remove the dialogs tab with all of its contents.

**Comment by Hackerfiera** [comment]
i replaced that, should i make anything more?

**Comment by Monniasza** [comment]
@Hackerfiera Have you replaced calls properly? I didn't see you make any changes in the chatter.

**Comment by Hackerfiera** [comment]
I don't understand, you told me "_Replace calls to openDialogWindow() with openAndShowWindow() and closeDialogWindow() with closeWindow() and remove the dialogs tab with all of its contents_." and I do this:

**Comment by Monniasza** [comment]
@Hackerfiera You have not supplied an image, only the placeholder for it.

**Comment by Hackerfiera** [comment]
I'm sorry, my internet is bad and it didn't upload, I'm sending it to you now, it's simply so you can see that I have changed the calls to the ones you told me.
image

**Comment by Monniasza** [comment]
@Hackerfiera Replace the calls in all callers. As a guide, mark declarations of methods that are to be replaced with `@Deprecated`.

**Comment by Hackerfiera** [comment]
Ok, I just did another push with the methods that I had forgotten to change, they are all in theory.
I think nothing is missing, you tell me

**Comment by Monniasza** [comment]
@Hackerfiera Great job, now calls are replaced properly, but do tabbed windows work properly?

**Comment by Hackerfiera** [comment]
I don't know exactly how to check it because I don't know where I have to hit, because in the dialogue there is nothing, I have left what was initially there but it was all blue (you can see it in the images above) and as I didn't understand the dialogue, for the moment it is commented.
So for the moment the right panel that bothered you is removed.  ✅
The method calls have been changed ✅
But I don't know how I can check the tabbed windows, if you refer to the normal operation of the application yes, everything is the same, but if you refer to the dialog, it's commented in the code because I don't know exactly where to put it, I still don't understand you.

**Comment by Monniasza** [comment]
@Hackerfiera Try left cicking chatter and creative block placer

**Comment by Hackerfiera** [comment]
I'm sorry but I don't understand how and where you want the chat, I send you a screenshot of where I think you want it.
image
Please send me a picture or something to understand how you want it because it is obvious that I don't understand you well. If you want it as in the screenshot, I can put it, but it will be the same as it was originally, i.e. with all blue.

On the other hand, I don't understand what you mean by "creative block placer." Please can you explain it to me?

**Comment by Monniasza** [comment]
@Hackerfiera How does the chat dialog appear currently? If it appears like machine windows do, then it's okay.

**Comment by Monniasza** [comment]
@Hackerfiera For chatter, you should see a text field and two buttons. For the creative block placer, you should see three buttons.

**Comment by Hackerfiera** [comment]
Let's see, I don't know if you don't understand what I'm asking you or what, because I don't understand what you're asking me, now you want me to put the Chat as it is now (i.e. with the blue background without being able to do anything) below where I proposed, right?
Also, you want me to add a text box and 2 buttons where? what size? what exactly?
and how to place the creative block I should see 3 buttons? I don't even understand what the creative block is, and I don't understand the 3 buttons, buttons in general that appear in the middle of the screen?

Please be a bit clearer because I don't understand you and I have also asked a colleague and he doesn't understand you either. I would like to finish card #203 (Removig of side panel) and have it fixed.

**Comment by Monniasza** [comment]
@Hackerfiera Refactor the chatter and creative block placer UIs to extend from `GUITab` and then open them with openAndShowWindow(); and close them with closeWindow().

**Pull request merged**
