### PR TITLE
Implemented "New Pickaxes" feature

### LINKED ISSUE #127: New pickaxes
Add the following picaxes to widen the choice of mining equipment:
- stone - 150 durability, 1s to mine a block
- iron - 250 durability, 640ms to mine a block
- steel - 350 durability, 400 ms to mine a block
- stainless - 600 durability, 280 ms to mine a block

and change rudimentary to 200 durability

### PR DESCRIPTION
**Pull request by PKCPablo**
Fixes #127 
## Added the following pickaxes:
- Stone - 150 durability, 1s to mine a block
- Iron - 250 durability, 640ms to mine a block
- Steel - 350 durability, 400 ms to mine a block
- Stainless - 600 durability, 280 ms to mine a block

## Added textures, recipes and translation
- Stone Pickaxe
- Iron Pickaxe
- Steel Pickaxe

## Changed
- Rudimentary Pickaxe to 200 durability

### CODE REVIEW

**Comment by Monniasza** [comment]
@PKCPablo You have not linked PR to the issue.

**Comment by PKCPablo** [comment]
@Monniasza how i do that?

**Comment by Monniasza** [comment]
@PKCPablo Type "Fixes " before the issue number

**Comment by PKCPablo** [comment]
@Monniasza now it is i think

**Comment by Monniasza** [comment]
@PKCPablo You have not created the iron pickaxe, and used iron for one of steel pickaxe recipes.

**Comment by PKCPablo** [comment]
@Monniasza fixed

**Comment by Monniasza** [comment]
Translate pickaxes into Polish, creating entries in Polish dictionary.

**Comment by PKCPablo** [comment]
It's translated. I used DeepL to translate it, so check the translation in case it doesn't make sense.

**Comment by Monniasza** [comment]
@PKCPablo Items in recipes do not form nice columns.

**Comment by Monniasza** [comment]
@PKCPablo I've not finished refactoring. I'll suggest my refactoring after I'm done with it.

**Comment by Monniasza** [comment]
@PKCPablo Merge my repo into your pull request.

**Comment by PKCPablo** [comment]
@Monniasza how do I do that??

**Comment by Monniasza** [comment]
@PKCPablo click on "Sync fork" and confirm.

**Comment by PKCPablo** [comment]
@Monniasza i think it's now donw

**Comment by PKCPablo** [comment]
> @PKCPablo Items in recipes do not form nice columns.

oh, it appears nice for me:
image

**Comment by Monniasza** [comment]
@PKCPablo Set your tab width to 4 spaces.

**Comment by Monniasza** [comment]
@PKCPablo Add tags to pickaxes.

**Comment by PKCPablo** [comment]
@Monniasza where should I put the tags??

**Comment by Monniasza** [comment]
@PKCPablo Add them in the static initializer on the same line as other pickaxes.

**Comment by PKCPablo** [comment]
@Monniasza done!

**Pull request merged**
